---
title: "'Catch' no puede aparecer después de 'Finally' dentro de una instrucción 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 13b8ce225fe487b0c597a6fe81983543e5af535e
ms.sourcegitcommit: 558d78d2a68acd4c95ef23231c8b4e4c7bac3902
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/09/2019
ms.locfileid: "59311336"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' no puede aparecer después de 'Finally' dentro de una instrucción 'Try'
Una instrucción `Catch` aparece en el código después del elemento `Finally` que finaliza un bloque de instrucciones `Try` . `Catch` debe aparecer dentro de un bloque de instrucciones `Try...Catch...Finally` .  
  
 **Identificador de error:** BC30379  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1. Mueva la instrucción `Catch` a un lugar más adecuado del código.  
  
## <a name="see-also"></a>Vea también

- [Try...Catch...Finally (Instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
