---
title: La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 17e7817c608e9c3513e0320b62f42410613f33b0
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/23/2019
ms.locfileid: "61666045"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'
Las instrucciones`Throw` fuera de una instrucción `Catch` deben facilitar el nombre de un objeto de excepción.  
  
 **Identificador de error:** BC30666  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1. Especifique el nombre de un objeto de excepción que derive de `System.Exception`.  
  
2. Reestructure el código para que la instrucción `Throw` se encuentre dentro de un bloque `Catch` .  
  
## <a name="see-also"></a>Vea también

- [Throw (instrucción)](../../visual-basic/language-reference/statements/throw-statement.md)
- [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Controlar y generar excepciones en .NET](../../standard/exceptions/index.md)
